Service:
  RegionId: cn-hangzhou
  DeployType: ros
  TenantType: SingleTenant
  DeployMetadata:
    AllowedRegions:
      - cn-hangzhou
      - cn-hongkong
    ServiceInstanceNameRule:
      Prefix: mariadb
    SupplierDeployMetadata:
      RoleName: ${RoleName}
      UserType: Aliyun
      SupplierTemplateConfigs:
        - Name: mariadb
          AllowedRegions:
            - ${RegionId}
          Url: 'templates/template.yaml'
          PredefinedParameters:
            - Name: 低配版
              Description: 1c1g
              Parameters:
                Vcpu: "1"
                Memory: 1Gi
                Storage: 20Gi
              Type: Normal
              OrderList:
                - Vcpu
                - Memory
                - Storage
            - Name: 基础版
              Description: 2c2g
              Parameters:
                Vcpu: "2"
                Memory: 2Gi
                Storage: 40Gi
              Type: Normal
              OrderList:
                - Vcpu
                - Memory
                - Storage
            - Name: 高配版
              Description: 2c4g
              Parameters:
                Vcpu: "2"
                Memory: 4Gi
                Storage: 80Gi
              Type: Normal
              OrderList:
                - Vcpu
                - Memory
                - Storage
          HiddenParameterKeys:
            - ClusterId
            - Vcpu
            - Memory
            - Storage
            - ConfigParam
          ParameterMappings:
            - ParameterKey: RegionId
              ParameterMappingKeys:
                - ClusterId
              ParameterValueMapping:
                ${RegionId}:
                  Parameters:
                    ClusterId: ${ClusterId}
    TemplateConfigs:
      - Name: mariadb
        AllowedRegions:
          - ${RegionId}
  OperationMetadata:
    ParameterConfigs:
      - TemplateName: mariadb
        Parameters:
          max_allowed_packet:
            Type: String
            Description: mysql服务器允许最大接收数的据包大小
            Default: '16M'
            ConstraintDescription: 8M~512M
          max_connections:
            Type: Number
            Description: 最大连接数
            Default: '512'
            ConstraintDescription: 256~1024
          max_user_connections:
            Type: Number
            Default: '48'
            Description: 用户最大的连接数
            ConstraintDescription: 32~64
          thread_cache_size:
            Type: Number
            Default: '16'
            Description: 线程缓存
            ConstraintDescription: 8,16,32,64
        Metadata:
          ParameterGroups:
            - Parameters:
                - max_allowed_packet
                - max_connections
                - max_user_connections
                - thread_cache_size
              TemplateParameter: ConfigParam
              DefaultValue: |-
                [mysqld]
                bind-address=*
                default_storage_engine=InnoDB
                binlog_format=row
                innodb_autoinc_lock_mode=2
                datadir=/data1/mysql
                socket=/data1/mysql/mysql.sock
                max_allowed_packet  = 256M
                max_connections  = 512
                max_user_connections = 50
                thread_cache_size = 16
                symbolic-links=0
                sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES

                [client]
                port=3306
                socket=/data1/mysql/mysql.sock
              Formatter: cnf
              FormatterConfig:
                SectionName: mysqld
    PrometheusIntegrationType: cn-mariadb
    PrometheusConfigMap:
      mariadb:
        EnablePrometheus: true
        GrafanaDashBoardTitle: MySQL Exporter Quickstart and Dashboard
        GrafanaDashBoardUrl: https://g.console.aliyun.com/d/549c2bf8936f7767ea6ac47c47b00f2a/mysql-exporter-quickstart-and-dashboard?orgId=355401&refresh=10s&var-datasource=cloud-product-prometheus_cn-hongkong_cn-mariadb_1563457855438522_135830&var-job=All&var-instance=All
  ServiceType: managed
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: MariaDB ACK容器多租户yaml部署
    Image: 'icons/mariadb.jpeg'
    Name: MariaDB ACK容器yaml部署
  ShareType: Public
  ApprovalType: Manual